In [1]:
# CS313.O21.KHCL
# Nguyễn Hoàng Tân - 21521413
# A2 Logistic Regresison

In [2]:
import pandas as pd  
import matplotlib.pyplot as plt  
import seaborn as sns  
import numpy as np 
import matplotlib.lines as mlines
import math
from sklearn import metrics
from sklearn.model_selection import train_test_split

In [3]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))


In [4]:
data = pd.read_csv("Social_Network_Ads.csv")
gender_map = {"Male": 0, "Female": 1}
data["Gender"] = data["Gender"].apply(lambda x: gender_map[x])

In [5]:
data

User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510       0   19            19000          0
1    15810944       0   35            20000          0
2    15668575       1   26            43000          0
3    15603246       1   27            57000          0
4    15804002       0   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863       1   46            41000          1
396  15706071       0   51            23000          1
397  15654296       1   50            20000          1
398  15755018       0   36            33000          0
399  15594041       1   49            36000          1

[400 rows x 5 columns]

In [6]:
data = data.values
N, d = data.shape
X = data[:, 0:d-1].reshape(-1, d-1)
y = data[:, -1].reshape(-1, 1)

In [7]:
N

400

In [8]:
X

array([[15624510,        0,       19,    19000],
       [15810944,        0,       35,    20000],
       [15668575,        1,       26,    43000],
       ...,
       [15654296,        1,       50,    20000],
       [15755018,        0,       36,    33000],
       [15594041,        1,       49,    36000]])

In [9]:
X_train,X_test,y_train,y_test = train_test_split(X,y,train_size=0.7,random_state=21521413)

In [10]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [11]:
X_train[:10]

array([[ 0.67762911,  0.97879618, -0.7409616 ,  0.3217927 ],
       [ 0.47659859,  0.97879618,  1.04513524, -0.87200598],
       [-1.29609179,  0.97879618,  0.19908937, -0.24526167],
       [ 0.05673755,  0.97879618, -0.55295141,  1.45590144],
       [ 1.69692608, -1.02166316, -0.27093612, -1.43906035],
       [ 0.98866541, -1.02166316, -0.08292592,  0.26210276],
       [ 0.13169165, -1.02166316, -0.17693102,  0.91869203],
       [-0.76429874, -1.02166316,  2.0791913 , -0.78247108],
       [-1.67994506,  0.97879618, -1.11698199,  0.35163766],
       [ 0.02264194,  0.97879618,  0.76311995, -0.81231605]])

In [12]:
y_train[:10]

array([[0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1]])

In [13]:
N_train = X_train.shape[0]

In [14]:
N_train

280

In [15]:
X_train = np.hstack((np.ones((N_train, 1)), X_train))

w = np.array([0.,0.1,0.1,0.1,0.1]).reshape(-1,1)

# Số lần lặp bước 2
numOfIteration = 10000
cost = np.zeros((numOfIteration,1))
learning_rate = 0.05

for i in range(1, numOfIteration):
    
	 # Tính giá trị dự đoán
    y_predict = sigmoid(np.dot(X_train, w))
    cost[i] = -np.sum(np.multiply(y_train, np.log(y_predict)) + np.multiply(1-y_train, np.log(1-y_predict)))
    # Gradient descent
    w = w - learning_rate * np.dot(X_train.T, y_predict-y_train)	 
    #print(cost[i])
print(cost[-1])

[93.11503898]


In [16]:
w

array([[-1.12545785],
       [-0.18921161],
       [ 0.01744684],
       [ 2.76948434],
       [ 1.09726823]])

In [17]:
X_test = np.hstack((np.ones((X_test.shape[0], 1)), X_test))

In [18]:
y_predict = sigmoid(np.dot(X_test, w)) >= 0.5  # Convert probabilities to 0 or 1
y_predict = y_predict.astype(int)  # Ensure predictions are integers (0 or 1)

# Calculate accuracy
accuracy = np.mean(y_predict == y_test) * 100

In [19]:
accuracy

82.5

In [20]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, y_predict))
from sklearn.metrics import classification_report
print(classification_report(y_test, y_predict))

[[68 12]
 [ 9 31]]
              precision    recall  f1-score   support

           0       0.88      0.85      0.87        80
           1       0.72      0.78      0.75        40

    accuracy                           0.82       120
   macro avg       0.80      0.81      0.81       120
weighted avg       0.83      0.82      0.83       120

